### ISSUE TITLE
[#2] 공동 컴포넌트 구현 - Image Slider

### ISSUE THREAD

**Issue by ekdms5566** [R3act-lion/YOURTRIP#3]
☝️ Issue Number : #2

📸 스크린샷
![image](https://user-images.githubusercontent.com/78911818/208605436-dfc31687-ccb4-44e8-9403-a7b486b4209d.png)

- [X] 기능 추가 (Feat)  : 이미지 모듈, 이미지 슬라이더 제작

**Comment by jattett** [comment]
짝짝짝!!
